packages:
  - .
  - packages/*

peerDependencyRules:
  ignoreMissing:
    - '@nuxt/kit'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - 'better-sqlite3'
  - 'sharp'
  - 'unrs-resolver'
  - 'vue-demi'

onlyBuiltDependencies:
  - 'esbuild'
  - 'workerd'
